name: sportify
description: Sistem booking lapangan olahraga terintegrasi
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  intl: ^0.18.0
  uuid: ^3.0.7
  ionicons: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LogoSportify.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/LogoSportify.png"


flutter:
  uses-material-design: true
  assets:
    - assets/LogoSportify.png
    - assets/

  