name: sportify
description: Sistem booking lapangan olahraga terintegrasi
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.0
  intl: ^0.18.0
  uuid: ^3.0.7
  ionicons: ^0.2.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  pdf: ^3.10.4
  printing: ^5.10.1
  animations: ^2.0.8
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LogoSportify.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/LogoSportify.png"


flutter:
  uses-material-design: true
  assets:
    - assets/LogoSportify.png
    - assets/

  